### ISSUE TITLE
서비스 초기에 우리가 관리할 게시판 목록 정하기

### ISSUE THREAD

**Issue by 9beach** [peirce-io/judys#1]
처음에 우리가 제시하는 방향이 서비스의 성공 여부에 큰 영향을 미친다. 물론 결국는 적극적인 사용자에의해 많이 좌우되지만. 기술적으로 추가해야할 것도 많지만 우선 게시판의 목록을 정해서 운영해가면서 최종안을 확정해야 한다. 이 티켓은 이에 따라 리오픈되고 클로즈되는 것을 반복할 것이다.
- 산출물 링크: [subreddits-and-descriptions](https://github.com/peirce-io/judys/wiki/subreddits-and-descriptions)

**Comment by joybro** [comment]
/r/judys.io -> /r/judys 게시판 이름이 점 찍으려면 디비 수정이 필요한듯 합니다. 일단 그냥 만들죠

**Comment by 9beach** [comment]
closed beta는 레이블보다는 마일스톤에 어울려요.
